# ARG USER=esy9d7l1

FROM ubuntu:18.04

RUN apt-get update -y && apt-get -y upgrade

RUN apt-get install python3.8 -y

RUN apt-get upgrade python3 -y

RUN apt-get install python3-pip -y

#RUN groupadd $USER --gid 1001 && useradd $USER --uid 1001 -g 1001

# RUN mkdir /home/$USER/scripts && chown $USER:$USER /home/$USER/scripts

# VOLUME /home/$USER/scripts

# USER $USER
